### ISSUE TITLE
Grub timeout regardless of settings

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os-patches#178]
## What Happened

We're still getting a forced grub timeout in OS 6 images. I've tested Ubuntu 20.04 on the same hardware with the same settings and do not get a forced grub screen there. It's also the same with and without full disk encryption enabled.

## Expected Behavior

Grub doesn't show by default, but only shows on boot failure or holding a key down (like Ubuntu).

## Steps to Reproduce

1. Install OS 6 Beta 2
2. Boot your new install
3. See grub

## Platform Information

OS 6 Beta 2

**Comment by abrattic** [comment]
There is a condition in `/boot/grub/grub.cfg` on line 104 that sets the timeout to 30, if the timeout in `/etc/default/grub` is set to 0.

For more information: https://askubuntu.com/a/1036957

**Comment by Kisuke-CZE** [comment]
I had same prolem with father's PC after fresh installation of Linux Mint 20, which is like elementaryOS based on Ubuntu 20.04 LTS.

Solution was this: https://forums.linuxmint.com/viewtopic.php?f=46&t=287026#p1588204

**Comment by lazarus-cm** [comment]
Will this be fixed and release before the Release Candidate does anyone know?

**Comment by TommyLuco** [comment]
I fixed it.
The issue is that you guys have a couple of different grub.cfg files. The one affecting the startup times is hidden in /boot/efi/EFI/ubuntu/grub/grub.cfg

I've set the timeout to 0 in that one and it affected the boot time.

No offense but might be the time to maybe clean up the whole grub setup.

**Comment by tomaswarynyca** [comment]
The problem is still present in the final version @cassidyjames

**Comment by tomaswarynyca** [comment]
I found a solution @hotsezus 

```
sudo sh -c 'echo GRUB_RECORDFAIL_TIMEOUT=0 >> /etc/default/grub';
sudo grub-mkconfig -o /boot/efi/EFI/ubuntu/grub/grub.cfg
```

**Comment by cassidyjames** [comment]
@tomaswarynyca I'm unable to reproduce. Can you provide more information about your install? Legacy/BIOS mode or EFI? Encryption? Secure boot?

**Comment by tomaswarynyca** [comment]
Sure @cassidyjames, my notebook is ASUS-X512DA
I have EFI, Secure boot & Encryption
Up I put the command that fixes it, there's a line to be set

**Comment by emcek** [comment]
I have same problem at my HP Probook 640 G2 with EFI and full disk encryption (not sure if about secure boot but 90% is on)

**Comment by bobcatzoo** [comment]
> @tomaswarynyca I'm unable to reproduce. Can you provide more information about your install? Legacy/BIOS mode or EFI? Encryption? Secure boot?

I installed on my second SSD drive, EFI and disabled Secure boot(thinkpad P52), every time I update /etc/default/grub time out setting and update-grub, It still 30s countdown. Also I think maybe this also the reason of black screen when logging in after suspend. Beside after I install VMware 16, when first launch it, VMware ask me to locate the kernel-5.11.... But when I switch to Ubuntu 20.04.2, these problems mentioned above doesn't appear. 

Hope this will be useful to solve the problem.

**Comment by davidmhewitt** [comment]
This should now be resolved after a round of system updates and another `update-grub`. Please comment if not.

**Comment by tomaswarynyca** [comment]
@davidmhewitt Why are you closing this? It's not related to your patch.
The solution I found was to add this line
https://github.com/elementary/os-patches/issues/178#issuecomment-896769076

**Comment by davidmhewitt** [comment]
> @davidmhewitt Why are you closing this? It's not related to your patch.
> The solution I found was to add this line [#178 (comment)](https://github.com/elementary/os-patches/issues/178#issuecomment-896769076)

So we've dropped the Ubuntu patch that's enabling that recordfail timeout (https://github.com/elementary/os-patches/pull/186), and we've fixed the issue that's causing `update-grub` to write config to the wrong place (#196), which is both lines of your workaround in your linked comment.

It's possible that there is yet another cause for this issue, so I'll re-open for now, but this _should_ be solved.

**Comment by tomaswarynyca** [comment]
If I remove `GRUB_RECORDFAIL_TIMEOUT=0` from `/etc/default/grub` the grub displays 30s

**Comment by davidmhewitt** [comment]
I'm going to close this now as I've confirmed this to be resolved on my own hardware using LVM and secure boot. I don't need to apply any workarounds and the timeout is no longer present after a fresh install with the latest version of our patched grub installed.

**Comment by Iveon** [comment]
Hi guys. I'm late.

add `GRUB_RECORDFAIL_TIMEOUT=$GRUB_TIMEOUT`  in `/etc/default/grub `works.

**Comment by FusionDragon** [comment]
Having this issue with elementary os 7

**Comment by Kisuke-CZE** [comment]
Probably same issue on all Ubuntu derivates for years. It appears if you are booting with EFIBOOT.
Had this issue on ElementaryOS 6, same applies for last 2 versions of Linux Mint.

Solution is by my experience:
```
sudo sh -c 'echo GRUB_RECORDFAIL_TIMEOUT=0 > /etc/default/grub.d/51_fix_efiboot.cfg';
sudo update-grub
```

**Comment by Odi-3** [comment]
So what should we elementary os 7 users do? Should we wait for an update? @davidmhewitt

**Comment by dmatavel** [comment]
Perhaps the issue should be re-opened since Elementary OS 7 Horus is having the same problem.

**Comment by Invarianz** [comment]
I'm facing the same issue on Elementary OS 7.1 Horus. The GRUB Timeout Settings do not get reflected in the grub config. I still get 30s of timeout regardless of any changes in `/etc/default/grub` followed by `sudo update-grub`.
