### ISSUE TITLE
Grub timeout 10 seconds regardless of settings

### ISSUE THREAD

**Issue by kdwk** [elementary/os-patches#193]
## What Happened

GRUB_DEFAULT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""

Then ran `sudo update-grub`

However, when I restart my computer GRUB still insisted on counting down: 10... 9... 8...

## Expected Behavior

When I set 'GRUB_TIMEOUT' to be 0, GRUB timeout should be zero seconds, not zero plus ten seconds

## Steps to Reproduce

1. 
2.
3.

## Platform Information

HP ProDesk 600 G5 Business PC ('protected by HP SureStart')
grub-efi-amd64 2.04-1ubuntu44.2

**Comment by davidmhewitt** [comment]
This should now be resolved after a round of system updates and another `update-grub`. Please comment if not.

**Comment by kdwk** [comment]
Grub is gone — finally :-) ! But Plymouth (the spinner) is still not showing up :-(

**Comment by casasfernando** [comment]
I'm still having this issue.

Even doe my Grub timeout in /etc/default/grub is set to 0, Grub is waiting 30 seconds to boot the default option.
My system is up to date and I just tried to run `sudo update-grub` to no avail.

```
# If you change this file, run 'update-grub' afterwards to update
# /boot/grub/grub.cfg.
# For full documentation of the options in this file, see:
#   info -f grub -n 'Simple configuration'

GRUB_DEFAULT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX="i915.enable_psr=0"

# Uncomment to enable BadRAM filtering, modify to suit your needs
# This works with Linux (no patch required) and with any kernel that obtains
# the memory map information from GRUB (GNU Mach, kernel of FreeBSD ...)
#GRUB_BADRAM="0x01234567,0xfefefefe,0x89abcdef,0xefefefef"

# Uncomment to disable graphical terminal (grub-pc only)
#GRUB_TERMINAL=console

# The resolution used on graphical terminal
# note that you can use only modes which your graphic card supports via VBE
# you can see them in real GRUB with the command `vbeinfo'
#GRUB_GFXMODE=640x480
GRUB_GFXMODE=1920x1440

# Uncomment if you don't want GRUB to pass "root=UUID=xxx" parameter to Linux
#GRUB_DISABLE_LINUX_UUID=true

# Uncomment to disable generation of recovery mode menu entries
#GRUB_DISABLE_RECOVERY="true"

# Uncomment to get a beep at grub start
#GRUB_INIT_TUNE="480 440 1"
GRUB_ENABLE_CRYPTODISK=y
```

Grub packages version:

```
grub-common/focal,now 2.04-1ubuntu26.13+elementary9~ubuntu6.1 amd64 [installed,automatic]
grub-efi-amd64-bin/focal-updates,now 2.04-1ubuntu44.2 amd64 [installed,automatic]
grub-efi-amd64-signed/focal-updates,now 1.167.2+2.04-1ubuntu44.2 amd64 [installed]
grub-efi-amd64/focal-updates,now 2.04-1ubuntu44.2 amd64 [installed]
grub-efi/focal,now 2.04-1ubuntu26.13+elementary9~ubuntu6.1 amd64 [installed]
grub2-common/focal,now 2.04-1ubuntu26.13+elementary9~ubuntu6.1 amd64 [installed,automatic]
```

**Comment by casasfernando** [comment]
Finally I solved by adding `GRUB_RECORDFAIL_TIMEOUT=0` to /etc/default/grub and then running `sudo update-grub` as mentioned in https://github.com/elementary/os-patches/issues/178#issuecomment-896769076.
